on: [push]
name: Lint

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Static Check
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
      - name: Vet
        run: go vet -v ./...
